name: Preview documentation build

on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  CLICOLOR: 1

concurrency: preview-${{ github.ref }}

permissions: {}

jobs:
  run:
    # Don't run for PRs from forks which fails due to lack of permissions.
    if: github.event.pull_request.head.repo.full_name == github.repository
    # Grant GITHUB_TOKEN the permissions required to make a gh-pages deployment
    permissions:
      contents: write  # to let mkdocs write the new docs
      pages: write     # to deploy to Pages
      id-token: write  # allow to generate an OpenID Connect (OIDC) token
      pull-requests: write  # add comment on the PR with the preview URL
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pyversion: ["3.13"]

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # https://github.com/actions/setup-python
      - name: Set up Python
        uses: actions/setup-python@v6.1.0
        with:
          
          python-version: ${{ matrix.pyversion }}
          
      # https://github.com/astral-sh/setup-uv
      - name: Install uv
        uses: astral-sh/setup-uv@v7.1.2
        with:
          
          python-version: ${{ matrix.pyversion }}
          
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install just
        run: |
          uv tool install rust-just

      - name: Install dependencies
        run: uv sync --dev --no-progress

      - name: Build documentation
        run: |
          just gen-doc
          uv run mkdocs build -d site
          touch site/.nojekyll

      # https://github.com/rossjrw/pr-preview-action
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1.6.3
        with:
          source-dir: site/
          preview-branch: gh-pages
